ShopBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        productNameEs:
            type: string
            length: 255
        productNameEn:
            type: string
            length: 255
        price:
            type: float
        priceA:
            type: float
        code:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: true
        foto:
            type: string
            length: 255
        isNew:
            type: boolean
        isShow:
            type: boolean
        isSale:
            type: boolean
        discountPrice:
            type: float
            nullable: true
        discountPriceA:
            type: float
            nullable: true
        isOferta:
            type: boolean
        maiUnit:
            type: integer
        suanUnit:
            type: integer
    oneToMany:
        colors:
            targetEntity: Color
            mappedBy: product
        sizes:
            targetEntity: Size
            mappedBy: product
        fotodetalles:
            targetEntity: Fotodetalle
            mappedBy: product
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: products
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
