ShopBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: ShopBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        isAutonomo:
            type: boolean
        timesCategory:
            type: array
    oneToOne:
        cart:
            targetEntity: Cart
            mappedBy: user
    oneToMany:
        orderInfos:
            targetEntity: OrderInfo
            mappedBy: user
    lifecycleCallbacks: {  }
