shop_user:
    resource: "@ShopBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

shop_category:
    resource: "@ShopBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category

shop_color:
    resource: "@ShopBundle/Resources/config/routing/color.yml"
    prefix:   /admin/color

shop_fotodetalle:
    resource: "@ShopBundle/Resources/config/routing/fotodetalle.yml"
    prefix:   /admin/fotodetalle

shop_product:
    resource: "@ShopBundle/Resources/config/routing/product.yml"
    prefix:   /admin/product

shop_size:
    resource: "@ShopBundle/Resources/config/routing/size.yml"
    prefix:   /admin/size

shop_orderinfo:
    resource: "@ShopBundle/Resources/config/routing/orderinfo.yml"
    prefix:   /admin/orderinfo

shop_orderitem:
    resource: "@ShopBundle/Resources/config/routing/orderitem.yml"
    prefix:   /admin/orderitem

shop_select:
    resource: "@ShopBundle/Resources/config/routing/select.yml"
    prefix:   /admin/select

shop_order:
    resource: "@ShopBundle/Resources/config/routing/order.yml"
    prefix:   /order

shop_product_font:
    resource: "@ShopBundle/Resources/config/routing/productfont.yml"
    prefix:   /product_font

shop_info:
    resource: "@ShopBundle/Resources/config/routing/info.yml"
    prefix:   /info

shop_sale:
    resource: "@ShopBundle/Resources/config/routing/sale.yml"
    prefix:   /admin/sale

shop_autonomo:
    resource: "@ShopBundle/Resources/config/routing/autonomo.yml"
    prefix:   /autonomo

shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }

shop_homepage_admin:
    path:     /admin
    defaults: { _controller: ShopBundle:Default:backEnd }
